"""Hand-curated pass-format classification for BPL's 22 museum passes.

`pass_format.json` is auto-generated by `scrape_pass_format.py` from the 13
Assabet libraries' master indexes; BPL uses LibCal so it's not part of that
scrape. This file fills the gap so BPL cells render the same ★ / ★★ markers
as the other libraries.

Classification source: per-pass page at https://bpl.libcal.com/passes/<id>,
keywords "RETURNABLE PASS" -> physical-circ, "does not need to be returned" or
"disposable pass" -> physical-coupon, anything else (e-coupon / e-ticket /
promo code / coupon code) -> digital.

Re-verify if BPL changes any pass terms.
"""

BPL_FMT = {
    # physical pass, must be picked up AND returned next day -> ★★
    "larz-anderson":            "physical-circ",
    "ma-state-parks":           "physical-circ",
    "trustees-of-reservations": "physical-circ",
    "zoo-new-england":          "physical-circ",

    # physical pass, pick up only, no return -> ★
    "harvard-museums":          "physical-coupon",
    "revolutionary-spaces":     "physical-coupon",

    # digital — e-coupon / e-ticket / promo code / coupon code -> no marker
    "american-rep-theater":     "digital",
    "boch-center":              "digital",
    "boston-childrens-museum":  "digital",
    "boston-harbor-islands":    "digital",
    "greenway-carousel":        "digital",
    "ica-boston":               "digital",
    "isabella-stewart-gardner": "digital",
    "mapparium":                "digital",
    "mass-audubon":             "digital",
    "mfa":                      "digital",
    "museum-of-science":        "digital",
    "new-england-aquarium":     "digital",
    "paddle-boston":            "digital",
    "peabody-essex-museum":     "digital",
    "sandwich-glass":           "digital",
    "uss-constitution-museum":  "digital",
}
