"""Slug + domain map for Assabet Interactive libraries.

Generated by build_slug_map.py — re-run that script and paste output if libraries
add or rename attractions.

OWNED_FOR_BOOKING is the set of libraries the user has *working* cards for —
used to color the calendar (green = at-least-one-of-mine; gray = exists only at
non-owned library; red = all libraries booked).

LIB_PRIORITY is the order to try when picking a default library for booking; the
user manually picks via the picker, but this affects the picker's button order.
"""

LIB_DOMAIN = {
    "wakefield":     "wakefieldlibrary.assabetinteractive.com",
    "stoneham":      "stonehamlibrary.assabetinteractive.com",
    "reading":       "readingpl.assabetinteractive.com",
    "woburn":        "woburnpubliclibrary.assabetinteractive.com",
    "lynnfield":     "lynnfieldlibrary.assabetinteractive.com",
    "peabody":       "peabodylibrary.assabetinteractive.com",
    "melrose":       "melrosepubliclibrary.assabetinteractive.com",
    "saugus":        "sauguspubliclibrary.assabetinteractive.com",
    "malden":        "maldenpubliclibrary.assabetinteractive.com",
    "medford":       "medfordlibrary.assabetinteractive.com",
    "burlington":    "burlington.assabetinteractive.com",
    "north-reading": "flintmemoriallibrary.assabetinteractive.com",
    "wilmington":    "wilmlibrary.assabetinteractive.com",
}

OWNED_FOR_BOOKING = ["reading", "wakefield", "wilmington"]
LIB_PRIORITY = OWNED_FOR_BOOKING

SLUG_MAP = {
    "american-heritage-museum": {"burlington": "american-heritage-museum", "stoneham": "american-heritage-museum"},
    "american-rep-theater": {"malden": "american-repertory-theater"},
    "aviation-museum-nh": {"north-reading": "the-aviation-museum-of-new-hampshire", "stoneham": "the-aviation-museum-of-new-hampshire"},
    "boston-by-foot": {"medford": "boston-by-foot", "north-reading": "boston-by-foot", "reading": "boston-by-foot", "wilmington": "boston-by-foot"},
    "boston-childrens-museum": {"burlington": "boston-childrens-museum", "lynnfield": "boston-childrens-museum", "malden": "boston-childrens-museum", "medford": "boston-childrens-museum", "melrose": "boston-childrens-museum", "peabody": "boston-childrens-museum", "reading": "boston-childrens-museum", "saugus": "boston-childrens-museum", "stoneham": "boston-childrens-museum", "wakefield": "boston-childrens-museum", "wilmington": "boston-childrens-museum", "woburn": "boston-childrens-museum"},
    "butterfly-place": {"burlington": "the-butterfly-place", "north-reading": "the-butterfly-place", "wilmington": "the-butterfly-place", "woburn": "the-butterfly-place"},
    "childrens-piazza": {"peabody": "the-childrens-piazza", "reading": "the-childrens-piazza", "saugus": "the-childrens-piazza"},
    "concord-museum": {"burlington": "concord-museum", "medford": "concord-museum", "reading": "concord-museum"},
    "davis-farmland": {"peabody": "davis-farmland", "wilmington": "davis-farmland"},
    "discovery-museum": {"burlington": "the-discovery-museums", "medford": "the-discovery-museums", "north-reading": "the-discovery-museums", "reading": "the-discovery-museums", "stoneham": "the-discovery-museums", "wilmington": "the-discovery-museums", "woburn": "the-discovery-museums"},
    "ecotarium": {"burlington": "ecotarium", "reading": "ecotarium"},
    "einsteins-workshop": {"wilmington": "einsteins-workshop"},
    "garden-in-the-woods": {"burlington": "garden-in-the-woods-native-plant-trust", "reading": "garden-in-the-woods-native-plant-trust"},
    "gore-place": {"burlington": "gore-place"},
    "greater-boston-stage": {"stoneham": "greater-boston-stage-company"},
    "griffin-museum": {"medford": "griffin-museum-of-photography"},
    "harvard-art-museums": {"melrose": "harvard-art-museums"},
    "harvard-museums": {"burlington": "harvard-museums-of-science-and-culture", "lynnfield": "harvard-museum-of-natural-history", "malden": "harvard-museum-of-natural-history", "medford": "harvard-museums-of-science-and-culture", "melrose": "harvard-museums-of-science-and-culture", "reading": "harvard-museum-of-natural-history", "saugus": "harvard-museums-of-science-and-culture", "wakefield": "harvard-museums-of-science-and-culture", "woburn": "harvard-museums-of-science-and-culture"},
    "historic-new-england": {"melrose": "historic-new-england", "reading": "historic-new-england", "stoneham": "historic-new-england"},
    "house-of-seven-gables": {"burlington": "the-house-of-seven-gables", "lynnfield": "the-house-of-seven-gables", "malden": "the-house-of-seven-gables", "medford": "the-house-of-seven-gables", "peabody": "the-house-of-seven-gables", "stoneham": "the-house-of-seven-gables", "wakefield": "the-house-of-seven-gables", "wilmington": "the-house-of-seven-gables", "woburn": "the-house-of-seven-gables"},
    "ica-boston": {"malden": "institute-of-contemporary-art-boston", "medford": "institute-of-contemporary-art-boston", "melrose": "institute-of-contemporary-art-boston", "north-reading": "institute-of-contemporary-art-boston", "reading": "institute-of-contemporary-art-boston", "wakefield": "institute-of-contemporary-art-boston", "wilmington": "institute-of-contemporary-art-boston"},
    "isabella-stewart-gardner": {"burlington": "isabella-stewart-gardner-museum", "lynnfield": "isabella-stewart-gardner-museum", "malden": "isabella-stewart-gardner-museum", "medford": "isabella-stewart-gardner-museum", "melrose": "isabella-stewart-gardner-museum", "north-reading": "isabella-stewart-gardner-museum", "peabody": "isabella-stewart-gardner-museum", "reading": "isabella-stewart-gardner-museum", "stoneham": "isabella-stewart-gardner-museum", "wakefield": "isabella-stewart-gardner-museum", "wilmington": "isabella-stewart-gardner-museum", "woburn": "isabella-stewart-gardner-museum"},
    "jfk-library": {"burlington": "john-f-kennedy-library-and-museum", "medford": "john-f-kennedy-library-and-museum", "melrose": "john-f-kennedy-library-and-museum", "reading": "john-f-kennedy-library-and-museum", "stoneham": "john-f-kennedy-library-and-museum", "wakefield": "john-f-kennedy-library-and-museum"},
    "ma-state-parks": {"burlington": "massachusetts-state-parks-department-of-conservation-and-recreation", "lynnfield": "massachusetts-state-parks-department-of-conservation-and-recreation", "malden": "massachusetts-state-parks-department-of-conservation-and-recreation", "medford": "massachusetts-state-parks-department-of-conservation-and-recreation", "north-reading": "massachusetts-state-parks-department-of-conservation-and-recreation", "peabody": "massachusetts-state-parks-department-of-conservation-and-recreation", "reading": "massachusetts-state-parks-department-of-conservation-and-recreation", "saugus": "massachusetts-state-parks-department-of-conservation-and-recreation", "stoneham": "massachusetts-state-parks-department-of-conservation-and-recreation", "wakefield": "massachusetts-state-parks-department-of-conservation-and-recreation", "wilmington": "massachusetts-state-parks-department-of-conservation-and-recreation", "woburn": "massachusetts-state-parks-department-of-conservation-and-recreation"},
    "mass-audubon": {"burlington": "mass-audubon-drumlin-farm", "medford": "mass-audubon", "melrose": "mass-audubon-drumlin-farm", "peabody": "mass-audubon", "wakefield": "mass-audubon", "wilmington": "mass-audubon-drumlin-farm", "woburn": "mass-audubon-drumlin-farm"},
    "merrimack-rep": {"wilmington": "merrimack-repertory-theatre"},
    "mfa": {"burlington": "museum-of-fine-arts", "lynnfield": "museum-of-fine-arts", "malden": "museum-of-fine-arts", "medford": "museum-of-fine-arts", "melrose": "museum-of-fine-arts", "north-reading": "museum-of-fine-arts", "peabody": "museum-of-fine-arts", "reading": "museum-of-fine-arts", "saugus": "museum-of-fine-arts", "stoneham": "museum-of-fine-arts", "wakefield": "museum-of-fine-arts", "wilmington": "museum-of-fine-arts", "woburn": "museum-of-fine-arts"},
    "museum-of-science": {"burlington": "museum-of-science", "lynnfield": "museum-of-science", "malden": "museum-of-science", "medford": "museum-of-science", "melrose": "museum-of-science", "north-reading": "museum-of-science", "peabody": "museum-of-science", "reading": "museum-of-science", "saugus": "museum-of-science", "stoneham": "museum-of-science", "wakefield": "museum-of-science", "wilmington": "museum-of-science", "woburn": "museum-of-science"},
    "naismith-basketball-hof": {"wilmington": "naismith-memorial-basketball-hall-of-fame"},
    "new-england-aquarium": {"burlington": "new-england-aquarium", "lynnfield": "new-england-aquarium", "malden": "new-england-aquarium", "medford": "new-england-aquarium", "melrose": "new-england-aquarium", "north-reading": "new-england-aquarium", "peabody": "new-england-aquarium", "reading": "new-england-aquarium", "saugus": "new-england-aquarium", "stoneham": "new-england-aquarium", "wakefield": "new-england-aquarium", "wilmington": "new-england-aquarium", "woburn": "new-england-aquarium"},
    "new-england-botanic-garden": {"burlington": "new-england-botanic-garden-at-tower-hill", "wilmington": "new-england-botanic-garden-at-tower-hill", "woburn": "new-england-botanic-garden-at-tower-hill"},
    "new-england-quilt-museum": {"burlington": "new-england-quilt-museum", "wilmington": "new-england-quilt-museum"},
    "north-shore-childrens-museum": {"burlington": "north-shore-childrens-museum", "lynnfield": "north-shore-childrens-museum", "melrose": "north-shore-childrens-museum", "north-reading": "north-shore-childrens-museum", "peabody": "north-shore-childrens-museum", "reading": "north-shore-childrens-museum", "saugus": "north-shore-childrens-museum", "wakefield": "north-shore-childrens-museum", "wilmington": "north-shore-childrens-museum"},
    "paddle-boston": {"medford": "paddle-boston", "reading": "paddle-boston", "stoneham": "paddle-boston"},
    "patriots-hall-of-fame": {"wilmington": "patriots-hall-of-fame"},
    "paul-revere-house": {"melrose": "paul-revere-house"},
    "peabody-essex-museum": {"burlington": "peabody-essex-museum", "lynnfield": "peabody-essex-museum", "malden": "peabody-essex-museum", "medford": "peabody-essex-museum", "melrose": "peabody-essex-museum", "north-reading": "peabody-essex-museum", "peabody": "peabody-essex-museum", "reading": "peabody-essex-museum", "stoneham": "peabody-essex-museum", "wakefield": "peabody-essex-museum", "wilmington": "peabody-essex-museum", "woburn": "peabody-essex-museum"},
    "plimoth-patuxet": {"peabody": "plimoth-patuxet-museums", "wakefield": "plimoth-patuxet-museums"},
    "salem-witch-museum": {"burlington": "salem-witch-museum", "reading": "salem-witch-museum", "stoneham": "salem-witch-museum", "wakefield": "salem-witch-museum", "wilmington": "salem-witch-museum", "woburn": "salem-witch-museum"},
    "sandmagination": {"medford": "sandmagination", "north-reading": "sandmagination", "wilmington": "sandmagination"},
    "trustees-of-reservations": {"burlington": "trustees-of-the-reservations", "lynnfield": "the-trustees-of-the-reservations", "malden": "the-trustees-of-the-reservations", "medford": "the-trustees-of-the-reservations", "melrose": "the-trustees-of-the-reservations", "north-reading": "the-trustees-of-the-reservations", "peabody": "the-trustees-of-the-reservations", "reading": "the-trustees-of-the-reservations", "stoneham": "trustees-of-the-reservations", "wakefield": "trustees-of-the-reservations", "wilmington": "the-trustees-of-the-reservations", "woburn": "the-trustees-of-the-reservations"},
    "uss-constitution-museum": {"burlington": "the-uss-constitution-museum", "lynnfield": "the-uss-constitution-museum", "malden": "the-uss-constitution-museum", "medford": "the-uss-constitution-museum", "melrose": "the-uss-constitution-museum", "north-reading": "the-uss-constitution-museum", "peabody": "the-uss-constitution-museum", "reading": "the-uss-constitution-museum", "saugus": "the-uss-constitution-museum", "wakefield": "the-uss-constitution-museum", "wilmington": "the-uss-constitution-museum", "woburn": "the-uss-constitution-museum"},
    "wenham-museum": {"peabody": "wenham-museum"},
    "zoo-new-england": {"burlington": "zoo-new-england", "lynnfield": "zoo-new-england", "malden": "zoo-new-england", "medford": "zoo-new-england", "melrose": "zoo-new-england", "north-reading": "zoo-new-england", "peabody": "zoo-new-england", "reading": "zoo-new-england", "saugus": "zoo-new-england", "stoneham": "zoo-new-england", "wakefield": "zoo-new-england", "wilmington": "zoo-new-england", "woburn": "zoo-new-england"},
}
